"""
tests/test_classifier.py
========================
Integration tests for the full routing pipeline.
SLM is mocked for deterministic, Ollama-independent testing.
"""
from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Make edgeroute importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from models.slm import SLMClassification, SLMResponse
from router.classifier import route, RoutingResult


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def _make_slm(route_val: str = "LOCAL_SIMPLE", conf: float = 0.95, error: str = "") -> MagicMock:
    """Create a mock LocalSLM that returns a canned classification."""
    slm = MagicMock()
    cls = SLMClassification(
        route=route_val,
        confidence=conf,
        reason=f"Mocked: {route_val}",
        intent="mocked intent",
        model_available=(error == ""),
        error=error,
    )
    slm.classify.return_value = cls
    slm.generate.return_value = SLMResponse(text=f"Generated by mock SLM for {route_val}")
    return slm


# ---------------------------------------------------------------------------
# Test 1 — Simple local query
# ---------------------------------------------------------------------------

def test_simple_local_query():
    slm = _make_slm("LOCAL_SIMPLE", 0.95)
    result = route("What is 2 + 2?", slm=slm)
    assert result.final_route == "LOCAL_SIMPLE"
    assert result.confidence >= 0.7
    assert result.response
    assert not result.privacy_blocked


# ---------------------------------------------------------------------------
# Test 2 — Local command routing
# ---------------------------------------------------------------------------

def test_local_command_routing():
    slm = _make_slm("LOCAL_COMMAND", 0.92)
    result = route("Turn on the bedroom light.", slm=slm)
    assert result.final_route == "LOCAL_COMMAND"
    assert result.tool_result is not None
    assert result.tool_result["status"] == "success"
    assert result.tool_result["tool"] == "turn_on_light"
    assert not result.privacy_blocked


# ---------------------------------------------------------------------------
# Test 3 — Complex query → CLOUD_COMPLEX
# ---------------------------------------------------------------------------

def test_complex_query_routes_to_cloud():
    slm = _make_slm("CLOUD_COMPLEX", 0.91)
    result = route("Write a 1500-word story about a civilization living on Mars.", slm=slm)
    assert result.final_route == "CLOUD_COMPLEX"
    assert not result.privacy_blocked


# ---------------------------------------------------------------------------
# Test 4 — Ambiguous query
# ---------------------------------------------------------------------------

def test_ambiguous_query():
    slm = _make_slm("AMBIGUOUS", 0.55)
    result = route("Help me with my project.", slm=slm)
    # With low confidence, policy will enforce deterministic fallback
    # May be AMBIGUOUS or whatever deterministic route picks
    assert result.final_route in ("AMBIGUOUS", "LOCAL_SIMPLE", "LOCAL_COMMAND", "CLOUD_COMPLEX")
    assert result.response  # Always has a response


# ---------------------------------------------------------------------------
# Test 5 — Low confidence → deterministic fallback
# ---------------------------------------------------------------------------

def test_low_confidence_triggers_deterministic_fallback():
    # SLM returns CLOUD_COMPLEX but with very low confidence
    slm = _make_slm("CLOUD_COMPLEX", 0.30)
    result = route("What is 2 + 2?", slm=slm)
    # Policy should override due to low confidence + simple signals
    assert result.final_route in ("LOCAL_SIMPLE", "AMBIGUOUS")
    assert result.policy.overridden or result.policy.override_reason


# ---------------------------------------------------------------------------
# Test 6 — Malformed SLM output → graceful fallback
# ---------------------------------------------------------------------------

def test_malformed_slm_output_handled_gracefully():
    slm = MagicMock()
    # SLM returns malformed result
    cls = SLMClassification(
        route="INVALID_ROUTE",
        confidence=0.99,
        reason="",
        error="json_parse_failure",
        model_available=True,
    )
    slm.classify.return_value = cls
    slm.generate.return_value = SLMResponse(text="fallback")

    result = route("What is 5 + 5?", slm=slm)
    # Should not crash and should produce a valid route
    assert result.final_route in ("LOCAL_SIMPLE", "LOCAL_COMMAND", "CLOUD_COMPLEX", "AMBIGUOUS")
    assert not result.error or result.final_route in ("AMBIGUOUS", "LOCAL_SIMPLE")


# ---------------------------------------------------------------------------
# Test 7 — Ollama unavailable → deterministic routing
# ---------------------------------------------------------------------------

def test_ollama_unavailable_deterministic_routing():
    slm = _make_slm(error="ollama_unavailable")
    slm.classify.return_value = SLMClassification(
        route="AMBIGUOUS",
        confidence=0.0,
        error="ollama_unavailable",
        model_available=False,
    )
    result = route("Turn on the light.", slm=slm)
    # Deterministic routing should detect command signal
    assert result.final_route in ("LOCAL_COMMAND", "AMBIGUOUS")
    assert not result.ollama_available


# ---------------------------------------------------------------------------
# Test 8 — Command override overrides SLM's misclassification
# ---------------------------------------------------------------------------

def test_command_override():
    # SLM incorrectly classifies as LOCAL_SIMPLE
    slm = _make_slm("LOCAL_SIMPLE", 0.85)
    result = route("Turn on the bedroom light.", slm=slm)
    # Policy should override to LOCAL_COMMAND due to command signal
    assert result.final_route == "LOCAL_COMMAND"
    assert result.tool_result is not None


# ---------------------------------------------------------------------------
# Test 9 — Privacy blocks cloud escalation
# ---------------------------------------------------------------------------

def test_privacy_blocks_cloud_escalation():
    slm = _make_slm("CLOUD_COMPLEX", 0.92)
    result = route("My email is user@example.com. Write a detailed report.", slm=slm)
    # Privacy guard should intercept and prevent CLOUD_COMPLEX
    assert result.final_route != "CLOUD_COMPLEX"
    assert result.privacy_blocked
    assert result.privacy.is_sensitive
    assert "email_address" in result.privacy.detected_patterns


# ---------------------------------------------------------------------------
# Test 10 — Empty query
# ---------------------------------------------------------------------------

def test_empty_query():
    slm = _make_slm()
    result = route("", slm=slm)
    assert result.final_route == "AMBIGUOUS"
    assert result.response


# ---------------------------------------------------------------------------
# Test 11 — All local tools route correctly
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("query,expected_tool", [
    ("Turn on the light", "turn_on_light"),
    ("Turn off the light", "turn_off_light"),
    ("Set the temperature to 22 degrees", "set_temperature"),
    ("Start the music", "start_music"),
    ("Lock the door", "lock_door"),
])
def test_all_local_tools(query: str, expected_tool: str):
    slm = _make_slm("LOCAL_COMMAND", 0.95)
    result = route(query, slm=slm)
    assert result.final_route == "LOCAL_COMMAND"
    assert result.tool_result is not None
    assert result.tool_result["tool"] == expected_tool


# ---------------------------------------------------------------------------
# Test 12 — Privacy detection for multiple patterns
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("query,expected_pattern", [
    ("My email is test@example.com", "email_address"),
    ("Call me at +1-555-867-5309", "phone_number"),
    ("Card number: 4111 1111 1111 1111", "credit_card_number"),
    ("password is hunter2", "inline_password"),
])
def test_privacy_pattern_detection(query: str, expected_pattern: str):
    slm = _make_slm("CLOUD_COMPLEX", 0.90)
    result = route(query, slm=slm)
    assert result.privacy_blocked
    assert expected_pattern in result.privacy.detected_patterns
